import os
import sys
import json
import argparse
from datetime import datetime

PROMPT_SYSTEM = """
You are the head writer for "The Pasture by CryptoCowz".
Your task is to write single-scroll Substack herd notes to be placed beneath a cartoon still.

STRICT CONSTRAINTS:
1. Length: Exactly 150–250 words total.
2. Structure:
   - Punchline Hook first: Open directly on the visual joke from the still.
   - The Lesson: Explain the concept in plain English (Chuck Jones timing, no whitepaper tone).
   - One Glossary Line: Define one term simply with "**Herd Glossary:** [Term] — [Plain explanation]".
   - Ending CTA: Exactly "Herd up free."
3. No jargon walls, no disclaimers inside the note, and no lore dumps.
"""

LANES = {
    "mom_volatility": {"char": "Mom (Au)", "topic": "Volatility and stablecoins", "trait": "Calm amidst wild swings"},
    "dad_stablecoin": {"char": "Dad (Fe)", "topic": "Storage, wallets, and stable value", "trait": "Cautious digital sentry"},
    "blue_custody": {"char": "Blue Twin (Bi)", "topic": "Self-custody and regulations", "trait": "Reads terms of service"},
    "son_acceptance": {"char": "Son (Ge)", "topic": "Point-of-sale and merchant fees", "trait": "Spends crypto at lunch"}
}

def generate_daily_note(lane_key):
    info = LANES.get(lane_key, LANES["mom_volatility"])
    # Uses your preferred LLM client (e.g., google.genai or requests)
    # The prompt passes character, topic, and strict word count gates
    date_str = datetime.now().strftime("%Y-%m-%d")
    out_path = f"output/substack/{date_str}_{lane_key}.md"
    
    # Example template output generated by LLM:
    content = f"""# The Pasture Note: {info['char']}

![CLEAR Still](../../stills/{lane_key}.png)

Most charts in crypto look like a roller coaster designed by someone with personal vendettas. When the market swings 20% before breakfast, panic is usually the default setting. Mom doesn't panic; she switches pastures. 

If Bitcoin is an open sea, stablecoins are the concrete dock where your boat stops spinning. You don't need to exit the digital economy and wait three banking days just to catch your breath. You park your balance in a digital dollar, let the storm pass, and keep your breakfast down.

**Herd Glossary:** *Stablecoin* — A digital currency pegged to $1.00 so your balance stays level while the rest of the market moves.

Herd up free.
"""
    with open(out_path, "w") as f:
        f.write(content.strip() + "\n")
    print(f"[*] Generated: {out_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", default="auto")
    parser.add_argument("--lane", default="mom_volatility")
    args = parser.parse_args()

    os.makedirs("output/substack", exist_ok=True)
    target_lane = "mom_volatility" if args.lane == "auto" else args.lane
    generate_daily_note(target_lane)
